# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import Reddit_pb2 as proto_dot_Reddit__pb2


class MockRedditStub(object):
    """
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/Reddit.proto
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/mockReddit.MockReddit/CreatePost',
                request_serializer=proto_dot_Reddit__pb2.Post.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.Post.FromString,
                )
        self.VotePost = channel.unary_unary(
                '/mockReddit.MockReddit/VotePost',
                request_serializer=proto_dot_Reddit__pb2.VoteRequest.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.VoteResponse.FromString,
                )
        self.VoteComment = channel.unary_unary(
                '/mockReddit.MockReddit/VoteComment',
                request_serializer=proto_dot_Reddit__pb2.VoteRequest.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.VoteResponse.FromString,
                )
        self.RetrievePost = channel.unary_unary(
                '/mockReddit.MockReddit/RetrievePost',
                request_serializer=proto_dot_Reddit__pb2.PostRequest.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.Post.FromString,
                )
        self.CreateComment = channel.unary_unary(
                '/mockReddit.MockReddit/CreateComment',
                request_serializer=proto_dot_Reddit__pb2.Comment.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.Comment.FromString,
                )
        self.GetTopComments = channel.unary_unary(
                '/mockReddit.MockReddit/GetTopComments',
                request_serializer=proto_dot_Reddit__pb2.TopCommentsRequest.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.TopCommentsResponse.FromString,
                )
        self.ExpandCommentBranch = channel.unary_unary(
                '/mockReddit.MockReddit/ExpandCommentBranch',
                request_serializer=proto_dot_Reddit__pb2.ExpandCommentBranchRequest.SerializeToString,
                response_deserializer=proto_dot_Reddit__pb2.ExpandCommentBranchResponse.FromString,
                )


class MockRedditServicer(object):
    """
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/Reddit.proto
    """

    def CreatePost(self, request, context):
        """Create a post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VotePost(self, request, context):
        """Upvote or downvote a post
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VoteComment(self, request, context):
        """Upvote or downvote a comment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrievePost(self, request, context):
        """Retrieve Post content
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComment(self, request, context):
        """Create a Comment
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopComments(self, request, context):
        """
        Retrieving a list of N most upvoted comments under a post, where N is a parameter to the call. The
        returned result should indicate whether there are replies under those comments.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandCommentBranch(self, request, context):
        """
        Expand a comment branch. This allows to open most N most upvoted comments under a given
        comment, alongside with N most upvoted comments under those comments. Essentially, a tree of
        depth 2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MockRedditServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=proto_dot_Reddit__pb2.Post.FromString,
                    response_serializer=proto_dot_Reddit__pb2.Post.SerializeToString,
            ),
            'VotePost': grpc.unary_unary_rpc_method_handler(
                    servicer.VotePost,
                    request_deserializer=proto_dot_Reddit__pb2.VoteRequest.FromString,
                    response_serializer=proto_dot_Reddit__pb2.VoteResponse.SerializeToString,
            ),
            'VoteComment': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteComment,
                    request_deserializer=proto_dot_Reddit__pb2.VoteRequest.FromString,
                    response_serializer=proto_dot_Reddit__pb2.VoteResponse.SerializeToString,
            ),
            'RetrievePost': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrievePost,
                    request_deserializer=proto_dot_Reddit__pb2.PostRequest.FromString,
                    response_serializer=proto_dot_Reddit__pb2.Post.SerializeToString,
            ),
            'CreateComment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComment,
                    request_deserializer=proto_dot_Reddit__pb2.Comment.FromString,
                    response_serializer=proto_dot_Reddit__pb2.Comment.SerializeToString,
            ),
            'GetTopComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopComments,
                    request_deserializer=proto_dot_Reddit__pb2.TopCommentsRequest.FromString,
                    response_serializer=proto_dot_Reddit__pb2.TopCommentsResponse.SerializeToString,
            ),
            'ExpandCommentBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandCommentBranch,
                    request_deserializer=proto_dot_Reddit__pb2.ExpandCommentBranchRequest.FromString,
                    response_serializer=proto_dot_Reddit__pb2.ExpandCommentBranchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mockReddit.MockReddit', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MockReddit(object):
    """
    python3 -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. proto/Reddit.proto
    """

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/CreatePost',
            proto_dot_Reddit__pb2.Post.SerializeToString,
            proto_dot_Reddit__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VotePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/VotePost',
            proto_dot_Reddit__pb2.VoteRequest.SerializeToString,
            proto_dot_Reddit__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VoteComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/VoteComment',
            proto_dot_Reddit__pb2.VoteRequest.SerializeToString,
            proto_dot_Reddit__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrievePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/RetrievePost',
            proto_dot_Reddit__pb2.PostRequest.SerializeToString,
            proto_dot_Reddit__pb2.Post.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/CreateComment',
            proto_dot_Reddit__pb2.Comment.SerializeToString,
            proto_dot_Reddit__pb2.Comment.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTopComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/GetTopComments',
            proto_dot_Reddit__pb2.TopCommentsRequest.SerializeToString,
            proto_dot_Reddit__pb2.TopCommentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExpandCommentBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mockReddit.MockReddit/ExpandCommentBranch',
            proto_dot_Reddit__pb2.ExpandCommentBranchRequest.SerializeToString,
            proto_dot_Reddit__pb2.ExpandCommentBranchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
